server:
  port: 8080
  tomcat:
    connection-timeout: 120000
    max-part-count: 50

originhub:
  ssh:
    port: 2222
    host-path: ${originhub.git.repo-root}/.hosts
    host-key-path: ${originhub.ssh.host-path}/ssh_host_key
  jwt:
    secret: ${ORIGINHUB_JWT_SECRET}
  frontend:
    base-url: ${ORIGINHUB_FRONTEND_BASE_URL:http://localhost:4200}
  git:
    repo-root: ${ORIGINHUB_GIT_REPO__ROOT:${user.home}/.originhub}

app:
  schema: public

spring:
  web:
    resources:
      static-locations: classpath:/static/
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: false
      republish-outstanding-events-on-restart: true
      completion-mode: update

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/originhub}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: ${app.schema}

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 6GB

  flyway:
    enabled: true
    schemas: public
    default-schema: public

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: Github
          gitlab:
            client-id: ${OAUTH2_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH2_GITLAB_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/gitlab"
            authorization-grant-type: authorization_code
            client-name: GitLab
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: id

logging:
  level:
    root: warn
